apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: awx23
  namespace: awx
spec:
  interval: 5m
  chart:
    spec:
      chart: awx-operator
      version: "2.5.2"
      sourceRef:
        kind: HelmRepository
        name: awx-operator
        namespace: awx
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
    AWX:
      enabled: true
      name: awx-demo
      spec:
        service_type: NodePort
        admin_user: admin
